var a = "1st feature commit"
var b = "2nd feature commit"
var c = "3rd feature commit"
var master2 = "2nd master commit"
let d = "4th feature commit"
let e = "5th feature commit"
let f = "6th feature commit"